# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags: -s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.date={{ .Date }}
    goos:
      - linux
      - windows
      - darwin

snapshot:
  name_template: "{{- .ShortCommit }}"

checksum:
  name_template: "{{- tolower .ProjectName }}-{{ .Version }}-checksums.txt"

archives:
  - format: tar.gz
    wrap_in_directory: true
    name_template: >-
      {{- tolower .ProjectName }}-
      {{- .Version }}-
      {{- tolower .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ tolower .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE-MIT
      - LICENSE-APACHE
      - README.md

sboms:
  - documents:
      - >-
        {{- tolower .ProjectName }}-
        {{- .Version }}-
        {{- tolower .Os }}-
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ tolower .Arch }}{{ end }}
        {{- if .Arm }}v{{ .Arm }}{{- end -}}{{- ".bom.json" -}}
    artifacts: binary
    cmd: cyclonedx-gomod
    args:
      - "app"
      - "-licenses"
      - "-json"
      - "-output"
      - "$document"
      - "-packages"
      - "-files"
      - "-licenses"
      - "../"
    env:
      - GOARCH={{ .Arch }}
      - GOOS={{ .Os }}

brews:
  - repository:
      owner: friendly-fhir
      name: homebrew-tap
    directory: Formula
    homepage: https://friendly-fhir.org/fhenix
    description: >
      Fhenix is a FHIR code-generation tool for producing language bindings from
      structure definitions
    install: |
      bin.install "fhenix"
      output = Utils.popen_read("#{bin}/fhenix completion bash")
      (bash_completion/"fhenix").write output
      output = Utils.popen_read("#{bin}/fhenix completion zsh")
      (zsh_completion/"_fhenix").write output
      output = Utils.popen_read("#{bin}/fhenixlint completion fish")
      (fish_completion/"fhenix.fish").write output
      prefix.install_metafiles
    test: |
      system "#{bin}/fhenix --version"
