name: Greet new contributor

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  greet:
    uses: friendly-fhir/.github/.github/workflows/community-greet-new-contributors.yaml@master
    permissions:
      contents: read
      issues: write
      pull-requests: write
