# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Continuous Integration

on:
  workflow_call:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  build-and-test:
    name: Build and Test
    uses: friendly-fhir/.github/.github/workflows/go-build-and-test.yaml@master
    with:
      packages: ./...
      go-version-file: go.mod
      short-test: false
    permissions:
      contents: read
      id-token: write

  integration-test:
    name: Integration Test
    uses: friendly-fhir/.github/.github/workflows/go-build-and-test.yaml@master
    with:
      packages: ./test/...
      go-version-file: ./test/go.mod
      short-test: false
      os-coverage-artifact-prefix: integration-coverage-
      coverage-artifact-name: integration-coverage
    permissions:
      contents: read
      id-token: write

  email-on-failure:
    name: Email on Failure
    runs-on: ubuntu-latest
    needs:
      - build-and-test
      - integration-test
    if: always() && failure()
    continue-on-error: true
    steps:
      - name: Send email
        uses: friendly-fhir/.github/actions/community/send-email@master
        with:
          recipient: ${{ secrets.CI_FAILURE_EMAIL_RECIPIENT }}
          api-key: ${{ secrets.MAILGUN_API_KEY }}
          subject: ${{ github.repository}} Continuous Integration failed
          body: |
            The Continuous Integration for ${{ github.repository }} failed.
            Please see ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} for details.
