# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Continuous Deployment

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  actions: read
  attestations: write
  contents: read
  id-token: write
  packages: write
  pages: write
  security-events: write

jobs:
  continuous-integration:
    name: Continuous Integration
    uses: ./.github/workflows/presubmit.yaml
    permissions:
      contents: read
      security-events: write
      id-token: write
      actions: read

  deploy-docker-container:
    name: Deploy Docker Container
    uses: friendly-fhir/.github/.github/workflows/docker-build-and-deploy-ghcr.yaml@master
    needs: continuous-integration
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

  deploy-pages:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    needs: continuous-integration

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Upload GH Pages
        id: deployment
        uses: actions/deploy-pages@v4

