# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and Deploy Container

on:
  push:
    tags:
      - "v*"
    branches:
      - master
      - develop

permissions:
  contents: read
  packages: write

jobs:
  deploy-docker-container:
    name: Deploy Docker Container
    uses: friendly-fhir/.github/.github/workflows/docker-build-and-deploy-ghcr.yaml@master
    permissions:
      contents: read
      packages: write
