# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  security-events: write
  id-token: write
  actions: read
  packages: write
  attestations: write

jobs:
  continuous-integration:
    name: Continuous Integration
    uses: ./.github/workflows/continuous-integration.yaml
    permissions:
      contents: read
      security-events: write
      id-token: write
      actions: read

  release-binaries:
    name: Release Binaries
    needs: continuous-integration
    uses: friendly-fhir/.github/.github/workflows/go-release.yaml@master
    with:
      snapshot: false
    permissions:
      contents: write
      attestations: write
      id-token: write

  release-container:
    name: Release Container Image
    needs: continuous-integration
    uses: friendly-fhir/.github/.github/workflows/docker-build-and-deploy-ghcr.yaml@master
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
